# Generated by Django 4.1.2 on 2022-11-06 18:32

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_customuser_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="account_value",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="buying_power",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(
                default="John Doe", max_length=30, verbose_name="User's name"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                default=django.utils.timezone.now,
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=20, verbose_name="User's password"),
        ),
    ]
